### ISSUE TITLE
PDP related error on each connection to the MN

### ISSUE THREAD

**Issue by sdruesedow** [reTHINK-project/dev-msg-node-nodejs#31]
I tried to execute the mn-tests for D6.4 against a fresh nodejs MN docker-image from the develop branch and see a PDP related error message on every websocket connection request:
```nodejs      | [2017-06-20 09:33:24.324] [INFO] server - [C->S] new client connection :  GCw-OU95Ktjd2QC3AAAr
nodejs      | [2017-06-20 09:33:24.329] [INFO] server - [C->S] new event :  {"id":1,"type":"open","from":"runtime://localhost/1","to":"mn:/session"}
nodejs      | [2017-06-20 09:33:24.331] [INFO] server - Error: [PDP PolicySet 1 | Policy 2 | Rule 2 Target] syntax error: unrecognized key in condition field: <actionType>!
nodejs      |     at Condition.isApplicable (/usr/src/app/src/main/components/policyEngine/Condition.js:97:23)
nodejs      |     at Rule.isApplicable (/usr/src/app/src/main/components/policyEngine/Rule.js:29:28)
nodejs      |     at Policy.evaluateRules (/usr/src/app/src/main/components/policyEngine/Policy.js:39:32)
nodejs      |     at PolicySet.evaluatePolicies (/usr/src/app/src/main/components/policyEngine/PolicySet.js:45:43)
nodejs      |     at PDP._respond (/usr/src/app/src/main/components/policyEngine/pdp/Pdp.js:52:34)
nodejs      |     at PDP.authorize (/usr/src/app/src/main/components/policyEngine/pdp/Pdp.js:35:21)
nodejs      |     at PEP.analyse (/usr/src/app/src/main/components/policyEngine/pep/Pep.js:37:37)
nodejs      |     at ClientMessage.dispatch (/usr/src/app/src/main/components/ClientMessage.js:61:39)
nodejs      |     at Client.processMessage (/usr/src/app/src/main/components/Client.js:53:21)
nodejs      |     at Socket.<anonymous> (/usr/src/app/src/main/MsgNode.js:161:16)
```
Could someone please have a look and give me instructions how to circumvent these problems?

**Comment by Heriam** [comment]
Hi @sdruesedow sorry for this problem, it is caused by unrecognized keyword in the policy.json file here: https://github.com/reTHINK-project/dev-msg-node-nodejs/blob/develop/src/main/components/policyEngine/prp/policy/policy.json. All the keywords marked with "<>" in the policy.json needs to be attributes in the Attributes.js file here: https://github.com/reTHINK-project/dev-msg-node-nodejs/blob/develop/src/main/components/policyEngine/Attributes.js. 
This issue here is caused by the mismatching of the keyword <actionType> in the policy.json and it actually should be <actType> as the one in the Attributes.js. 
I have accordingly changed the keyword <actionType> to <actType> in the development branch. 
The development branch now should not report such an error now.
Please feel free to report here if you meet with any other problem with the policy engine.

**Comment by sdruesedow** [comment]
Hi @Heriam! I did a quick first test with your updates and it seems to work now. I'll do some deeper tests tomorrow morning. Thanks a lot for your help!

**Comment by Heriam** [comment]
Hi @sdruesedow , you are very welcome. Please update here if you meet any other problem concernning the policy engine:)
